// <auto-generated />
using System;
using INDWalks.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace INDWalks.Migrations
{
    [DbContext(typeof(INDWalksDbContext))]
    partial class INDWalksDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("INDWalks.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9a4a37f-6f4d-4e3b-b0e7-a928bb4bf87b"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("4c04209b-8490-41f7-a97f-dd68618c6307"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("092600b8-e6ff-4bc5-b762-4b2f494a8510"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("INDWalks.Models.Domain.Regions", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1469cb3d-71fe-4133-a5ad-a466cc004edc"),
                            Code = "BR",
                            Name = "Bihar",
                            RegionImageUrl = "Bihar-state.jpg"
                        },
                        new
                        {
                            Id = new Guid("ebd40265-3712-42bc-9171-4808c250533a"),
                            Code = "DL",
                            Name = "New Delhi",
                            RegionImageUrl = "New-Delhi-state.jpg"
                        },
                        new
                        {
                            Id = new Guid("f85a8f88-a975-47f9-9f88-fcd6ddf9b4de"),
                            Code = "MH",
                            Name = "Maharastra",
                            RegionImageUrl = "Maharastra-state.jpg"
                        },
                        new
                        {
                            Id = new Guid("6a618c79-d331-49cd-a5f6-1a1e92fcc2bb"),
                            Code = "WB",
                            Name = "West-Bengal",
                            RegionImageUrl = ""
                        },
                        new
                        {
                            Id = new Guid("a7c091ca-79d7-47a8-b3f9-bb2b74155f56"),
                            Code = "TN",
                            Name = "Tamil Nadu",
                            RegionImageUrl = "Tamil-Nadu-state.jpg"
                        });
                });

            modelBuilder.Entity("INDWalks.Models.Domain.Walks", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uuid");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("INDWalks.Models.Domain.Walks", b =>
                {
                    b.HasOne("INDWalks.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("INDWalks.Models.Domain.Regions", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
